### ISSUE TITLE
Does this library work on Android? 

### ISSUE THREAD

**Issue by OmidNejadabbasi** [henkelmax/rnnoise4j#3]
### Bug description

Can this library work on Android or IOS ? 
Have you tested it on these platforms?

### Version

0.0.0

### Steps to reproduce

Can you try to compile it for android too ?

**Comment by henkelmax** [comment]
![image](https://github.com/user-attachments/assets/cb882228-2de0-468f-bed3-f17e94d60092)
These are all supported architectures. There are no plans on adding android support.

**Comment by OmidNejadabbasi** [comment]
@henkelmax  perhaps you can add the android build action to you github actoins. this is the script that worked for an old project of mine. also `build-java-lib` action is also updated accordingly: 

```yaml
name: build-android
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-android:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./rust
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y unzip

      - name: Install Android NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r27b-linux.zip
          unzip android-ndk-r27b-linux.zip
          echo "ANDROID_NDK_HOME=$GITHUB_WORKSPACE/android-ndk-r27b" >> $GITHUB_ENV
          echo "$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin" >> $GITHUB_PATH

      - name: Install Rust targets for Android
        run: |
          rustup target add aarch64-linux-android armv7-linux-androideabi i686-linux-android x86_64-linux-android

      - name: Cargo build for Android (AArch64)
        run: |
          export API_LEVEL=21
          export TARGET=aarch64-linux-android
          cargo ndk -t $TARGET -p $API_LEVEL build --release --lib
          
      - name: Cargo build for Android (ARMv7)
        run: |
          export API_LEVEL=21
          export TARGET=armv7-linux-androideabi
          cargo ndk -t $TARGET -p $API_LEVEL build --release --lib

      - name: Cargo build for Android (x86)
        run: |
          export API_LEVEL=21
          export TARGET=i686-linux-android
          cargo ndk -t $TARGET -p $API_LEVEL build --release --lib

      - name: Cargo build for Android (x86_64)
        run: |
          export API_LEVEL=21
          export TARGET=x86_64-linux-android
          cargo ndk -t $TARGET -p $API_LEVEL build --release --lib

      - name: Upload Android AArch64 artifact
        uses: actions/upload-artifact@v3
        with:
          name: rnnoise4j-android-aarch64
          path: ./rust/target/aarch64-linux-android/release/librnnoise4j.so

      - name: Upload Android ARMv7 artifact
        uses: actions/upload-artifact@v3
        with:
          name: rnnoise4j-android-armv7
          path: ./rust/target/armv7-linux-androideabi/release/librnnoise4j.so

      - name: Upload Android x86 artifact
        uses: actions/upload-artifact@v3
        with:
          name: rnnoise4j-android-x86
          path: ./rust/target/i686-linux-android/release/librnnoise4j.so

      - name: Upload Android x86_64 artifact
        uses: actions/upload-artifact@v3
        with:
          name: rnnoise4j-android-x86_64
          path: ./rust/target/x86_64-linux-android/release/librnnoise4j.so


build-java-library:
  runs-on: ubuntu-20.04
  needs: [build-linux-x86-64, build-linux-x86, build-linux-aarch64, build-macos-x86-64, build-macos-aarch64, build-windows-x86-64, build-windows-x86, build-android]
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java 8
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '8'
        server-id: henkelmax.public
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD

    - name: Download linux-x86-64
      uses: actions/download-artifact@v3
      with:
        name: rnnoise4j-linux-x86-64
        path: ./src/main/resources/natives/linux-x64/

    - name: Download linux-x86
      uses: actions/download-artifact@v3
      with:
        name: rnnoise4j-linux-x86
        path: ./src/main/resources/natives/linux-x86/

    - name: Download linux-aarch64
      uses: actions/download-artifact@v3
      with:
        name: rnnoise4j-linux-aarch64
        path: ./src/main/resources/natives/linux-aarch64/

    - name: Download macos-x86-64
      uses: actions/download-artifact@v3
      with:
        name: rnnoise4j-macos-x86-64
        path: ./src/main/resources/natives/mac-x64/

    - name: Download macos-aarch64
      uses: actions/download-artifact@v3
      with:
        name: rnnoise4j-macos-aarch64
        path: ./src/main/resources/natives/mac-aarch64/

    - name: Download windows-x86-64
      uses: actions/download-artifact@v3
      with:
        name: rnnoise4j-windows-x86-64
        path: ./src/main/resources/natives/windows-x64/

    - name: Download windows-x86
      uses: actions/download-artifact@v3
      with:
        name: rnnoise4j-windows-x86
        path: ./src/main/resources/natives/windows-x86/

    # **Added Android Downloads**

    - name: Download android-aarch64
      uses: actions/download-artifact@v3
      with:
        name: rnnoise4j-android-aarch64
        path: ./src/main/resources/natives/android-aarch64/

    - name: Download android-armv7
      uses: actions/download-artifact@v3
      with:
        name: rnnoise4j-android-armv7
        path: ./src/main/resources/natives/android-armv7/

    - name: Download android-x86
      uses: actions/download-artifact@v3
      with:
        name: rnnoise4j-android-x86
        path: ./src/main/resources/natives/android-x86/

    - name: Download android-x86_64
      uses: actions/download-artifact@v3
      with:
        name: rnnoise4j-android-x86_64
        path: ./src/main/resources/natives/android-x86_64/

    - name: Build and deploy
      run: |
        mvn -B install
        mkdir -p release
        cp $(find ./target -maxdepth 1 -type f -name "*.jar") ./release/
        mvn -B deploy
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}

    - uses: actions/upload-artifact@v3
      with:
        name: rnnoise4j-java
        path: ./release/

    - name: Upload release asset
      uses: AButler/upload-release-assets@v2.0.2
      with:
        files: ./release/*
        repo-token: ${{ secrets.GITHUB_TOKEN }}

```
